04-Stok.UI/Areas/Admin/Controllers/CategoryController.cs
using _01_Stok.Entities.Models.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace _04_Stok.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize] //yetkili
    public class CategoryController : Controller
    {
        private readonly HttpClient _httpClient; //api isteklerimi client nesnesi üzerinden gerçekleştiricem api repository uzerinden contextle konusacak

        public CategoryController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        string uri = "http://localhost:5056/api/category"; //apiye istek atacagım 

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            category.IsActive = true;
            var response = await _httpClient.PostAsJsonAsync($"{uri}/addcategory", category);
            if (response.IsSuccessStatusCode)
            {
                //// var newCategory = await response.Content.ReadFromJsonAsync<Category>(); gerek yok
                return RedirectToAction("List");
            }
            return View(category); 
        }

        public async Task<IActionResult> List()
        {
            var response = await _httpClient.GetAsync($"{uri}/getallcategory");
            if (response.IsSuccessStatusCode)
            {
                var categories = await response.Content.ReadFromJsonAsync<List<Category>>();
                return View(categories);
            }
            return View();
        }


        public async Task<IActionResult> Update(int id)
        {
            var response = await _httpClient.GetAsync($"{uri}/GetCategoryById/{id}");
            if (response.IsSuccessStatusCode)
            {
                var category = await response.Content.ReadFromJsonAsync<Category>();
                return View(category);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Category category)
        {
            var response = await _httpClient.PutAsJsonAsync($"{uri}/CategoryUpdate/{id}", category);
            if(response.IsSuccessStatusCode) return RedirectToAction(nameof(List));
            else return View(category);
        }

        public async Task<IActionResult> MakePassive(int id)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/DeleteCategory/{id}"); //apideki cat.cont.httpget idi
            if ((response.IsSuccessStatusCode))
            {
                return RedirectToAction(nameof(List));
            }
            return RedirectToAction("Index", "Home", new { area = "Admin" });
        }

        public async Task<IActionResult> MakeActive(int id)
        {
            var response = await _httpClient.GetAsync($"{uri}/MakeActiveCategory/{id}"); //apideki cat.cont.httpget idi
            if ((response.IsSuccessStatusCode))
            {
                return RedirectToAction(nameof(List));
            }
            return RedirectToAction("Index", "Home", new { area = "Admin" });

        }


        //supplier yapın, dto ve anotations




    }
}

04-Stok.UI/Areas/Admin/Controllers/ProductController.cs
using _01_Stok.Entities.Models.Concrete;
using _04_Stok.UI.Areas.Admin.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace _04_Stok.UI.Areas.Admin.Controllers
{
    [Area("Admin")] //Admin'in areasıdır
    [Authorize] //yetkili
    public class ProductController : Controller
    {
        private readonly HttpClient _httpClient;

        public ProductController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        string uri = "http://localhost:5056/api"; //apiye istek atacagım, bir yere kadar root aynı
        ProductCreateVM vm = new ProductCreateVM();

        public async Task<IActionResult> Create() //View'a giderken product bilgileri, elimdeki category ve supplier dan seçtirebilirim => productVM
        {
            //aktif kategorilerimi al
            var response = await _httpClient.GetAsync($"{uri}/category/GetActiveCategory");
            if (response.IsSuccessStatusCode)
            {
                var categories = await response.Content.ReadFromJsonAsync<List<Category>>();
                vm.Categories = categories.Select(a => new SelectListItem() {Text=a.CategoryName, Value=a.ID.ToString() }).ToList();
            }

            var responseSup = await _httpClient.GetAsync($"{uri}/supplier/GetAllActiveSuppliers");
            if (responseSup.IsSuccessStatusCode)
            {
                var suppliers = await responseSup.Content.ReadFromJsonAsync<List<Supplier>>();
                vm.Suppliers = suppliers.Select(a => new SelectListItem() { Text = a.SupplierName, Value = a.ID.ToString() }).ToList();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateVM vm)
        {
            var response = await _httpClient.PostAsJsonAsync($"{uri}/product/AddProduct", vm.Product);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return View(vm);
        }


        public async Task<IActionResult> List()
        {
            var response = await _httpClient.GetAsync($"{uri}/product/GetAllProduct");
            if (response.IsSuccessStatusCode)
            {
                var products = await response.Content.ReadFromJsonAsync<List<Product>>();
                return View(products);
            }
            return NoContent();
        }


        ProductUpdateVM uVm = new ProductUpdateVM();

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            //pozitif bir kod isvalid falan bakmadık
            var response = await _httpClient.GetAsync($"{uri}/product/GetProductById/{id}");
            if (response.IsSuccessStatusCode)
            {
                uVm.Product = await response.Content.ReadFromJsonAsync<Product>();
            }

            var responseC = await _httpClient.GetAsync($"{uri}/category/GetActiveCategory");
            if (responseC.IsSuccessStatusCode)
            {
                var categories = await responseC.Content.ReadFromJsonAsync<List<Category>>();
                uVm.Categories = categories.Select(a => new SelectListItem() { Text = a.CategoryName, Value = a.ID.ToString() }).ToList();
            }

            var responseSup = await _httpClient.GetAsync($"{uri}/supplier/GetAllActiveSuppliers");
            if (responseSup.IsSuccessStatusCode)
            {
                var suppliers = await responseSup.Content.ReadFromJsonAsync<List<Supplier>>();
                uVm.Suppliers = suppliers.Select(a => new SelectListItem() { Text = a.SupplierName, Value = a.ID.ToString() }).ToList();
            }
            return View(uVm);
        }

            //hatırlatma : pozitif bir kod, hata meydana gelip tekrar viewa giderse categories, suppliers null gelir!!!
            [HttpPost]
            public async Task<IActionResult> Update(ProductUpdateVM vm)
            {
                var response = await _httpClient.PutAsJsonAsync($"{uri}/product/UpdateProduct", vm.Product);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(List));
                }
                //categories - suppliers doldurman lazım
                return View(vm);
            }


        public async Task<IActionResult> MakePassive(int id)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/product/DeleteProduct/{id}");
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(List));
            else return RedirectToAction("Index", "Home", new { area = "Admin" });
        }


        public async Task<IActionResult> MakeActive(int id)
        {
            var response = await _httpClient.GetAsync($"{uri}/product/MakeActiveProduct/{id}");
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(List));
            else return RedirectToAction("Index", "Home", new { area = "Admin" });
        }


        
    }
}

04-Stok.UI/Areas/Admin/Controllers/SupplierController.cs
using _01_Stok.Entities.Models.Concrete;
using _04_Stok.UI.Areas.Admin.Models.SupplierDTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace _04_Stok.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize] //yetkili
    public class SupplierController : Controller
    {
        private readonly HttpClient _httpClient;

        public SupplierController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }



        string uri = "http://localhost:5056/api/supplier"; //apiye istek atacagım 

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SupplierCreateDTO supplierDto) //swagger da nesne mantıgı yok, json formatında çalıştığı için sorun yok fakat api olmasaydı supplier ın kendisini isterdi
        {
            supplierDto.IsActive = true;
            var response = await _httpClient.PostAsJsonAsync($"{uri}/addsupplier", supplierDto);//Api katman Sup.controller daki httppost, AddSupplier() metodu 
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return View(supplierDto);
        }

        public async Task<IActionResult> List() //json oldugu icin dto yu direk halletti
        {
            var response = await _httpClient.GetAsync($"{uri}/getallsupplier");
            if (response.IsSuccessStatusCode)
            {
                //var suppliers = await response.Content.ReadFromJsonAsync<List<Supplier>>();
                var suppliers = await response.Content.ReadFromJsonAsync<List<SupplierListDTO>>();

                return View(suppliers);
            }
            return View();
        }


        public async Task<IActionResult> Update(int id)
        {
            var response = await _httpClient.GetAsync($"{uri}/GetSupplierById/{id}");
            if (response.IsSuccessStatusCode)
            {
                var supplierUpdateDto = await response.Content.ReadFromJsonAsync<SupplierUpdateDTO>();
                return View(supplierUpdateDto);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, SupplierUpdateDTO supplierUpdateDto)
        {
            var response = await _httpClient.PutAsJsonAsync($"{uri}/SupplierUpdate/{id}", supplierUpdateDto);
            if (response.IsSuccessStatusCode) return RedirectToAction(nameof(List));
            else return View(supplierUpdateDto);
        }

        public async Task<IActionResult> MakePassive(int id)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/DeleteSupplier/{id}"); //apideki sup.cont.httpdelete DeleteSupplier idi
            if ((response.IsSuccessStatusCode))
            {
                return RedirectToAction(nameof(List));
            }
            return RedirectToAction("Index", "Home", new { area = "Admin" });
        }

        public async Task<IActionResult> MakeActive(int id)
        {
            var response = await _httpClient.GetAsync($"{uri}/MakeActiveSupplier/{id}"); //apideki sup.cont.httpget idi
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(List));
            }
            return RedirectToAction("Index", "Home", new { area = "Admin" });

        }


        //supplier yapın, dto ve anotations kullanın








    }
}

04-Stok.UI/Areas/User/Controllers/OrderController.cs
using _01_Stok.Entities.Models.Concrete;
using _04_Stok.UI.Areas.User.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace _04_Stok.UI.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    //Role check olmadıgı icin kayıtlı olan herkes/iceri giren herkes gorecek fakat role check eklersen calısır
    //[Authorize(Role="admin",] identiy kullansaydık
    public class OrderController : Controller
    {
        private readonly HttpClient _httpClient;

        public OrderController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        string uri = "http://localhost:5056/api";


        OrderVM vm = new OrderVM();

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var response = await _httpClient.GetAsync($"{uri}/product/GetActiveProduct");
            if (response.IsSuccessStatusCode)
            {
                var products = await response.Content.ReadFromJsonAsync<List<Product>>();
                vm.AvailableProducts = products;
                vm.OrderDetails = products.Select(a=> new OrderDetailVM() { ProductID = a.ID}).ToList();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderVM vm) //apideki ordercont add metodu çok parametre alıyor, nesne değil querystring göndereceğim
        {
            var id = User.Claims.FirstOrDefault(c=>c.Type==ClaimTypes.NameIdentifier).Value; //claims principal User'ı
            //value yazmayınca boş gitti ve hata oluştur
            var productsIds = vm.OrderDetails.Select(a=>a.ProductID).ToList();
            var productsQuantities = vm.OrderDetails.Select(a=>a.Quantity).ToList();

            //order cont. AddOrder metodunda FromQuery(http://localhost:3000/user?userId=5896544) var, url route(http://localhost:3000/user/5896544) vermedik, çoklu parametre ile : //Rsponse.Redirect("http://localhos/YourControllerName/ActionMethodName?querrystring1=querrystringvalue1&querrystring2=querrystringvalue2&querrystring3=querystringvalue3"); querystringle istediğin parametre alabiliyor, encode de olabiliyor
            var queryParams = $"?userId={id}&{string.Join("&", productsIds.Select((p, i) => $"productIDs={p}"))}&{string.Join("&", productsQuantities.Select((q, i) => $"quantities={q}"))}";


            var response = await _httpClient.PostAsync($"{uri}/order/AddOrder"+queryParams, null);//basit tiplerdeki digerlerindeki gibi nesneyi değil query stringi gönderdik

            if (response.IsSuccessStatusCode) return RedirectToAction("List");
            else return View(vm);
        }


        //public async Task<IActionResult> List()
        //{
        //    var response = await _httpClient.GetAsync($"{uri}/order/GetAllOrders");
        //    if(response.IsSuccessStatusCode)
        //    {
        //        var orders = await response.Content.ReadFromJsonAsync<List<Order>>();
        //        return View(orders);
        //    }
        //    return RedirectToAction("Index", "Home", new { area = "User" });
        //}

        public async Task<IActionResult> List()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            var response = await _httpClient.GetAsync($"{uri}/order/GetOrdersByUserId/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var orders = await response.Content.ReadFromJsonAsync<List<Order>>();
                return View(orders);
            }
            return RedirectToAction("Index", "Home", new { area = "User" });
        }


        //1-iceri giren user id sini alabildigimiz icin her user'ın kendi sayfasında kendi siparişlerini görücez
        //2-kendi siparişi geldiğnde order ını (sepetini) komple silebilir yada orderdetails ini update/delete edeblir.Database den de oldugunu  kontrol et.


        [HttpPost]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/order/DeleteOrder/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Index", "Home", new { area = "User" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateOrderDetail(OrderDetailVM orderDetail)
        {
            var response = await _httpClient.PutAsJsonAsync($"{uri}/order/UpdateOrderDetail", orderDetail);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Index", "Home", new { area = "User" });
        }


        [HttpPost]
        public async Task<IActionResult> DeleteOrderDetail(int id)
        {
            var response = await _httpClient.DeleteAsync($"{uri}/order/DeleteOrderDetail/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Index", "Home", new { area = "User" });
        }



    }
}

04-Stok.UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _04_Stok.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_04_Stok.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_04_Stok.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Kategori
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Create" >Kategori Ekle</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="List">Kategori List</a></li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Supplier
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Supplier" asp-action="Create">Supplier Ekle</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Supplier" asp-action="List">Supplier List</a></li>

                           
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ürünler
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Create">Ürün Ekle</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="List">Ürün List</a></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Siparişkolar
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="User" asp-controller="Order" asp-action="Create">Order Ekle</a></li>
                                <li><a class="dropdown-item" asp-area="User" asp-controller="Order" asp-action="List">Order List</a></li>

                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Logout">Çıkış Yap</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - _04_Stok.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@* dropdown kodunu bootstrap ten aldık *@